version: "3.8"
services:
  db: # database
    image: 'postgres'
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: giuseppe-28
      POSTGRES_USER: docker
    volumes:
      - data:/var/lib/postgresql/data # salvo i dati del database


  
  backend_exchange:
    build: ./backend_exchange
    container_name: backend_exchange_c
    ports:
      - '9000:9000'
      - '9001:9001'
      - '80:80'
  frontend_exchange: 
    build: ./frontend_exchange
    container_name: frontend_exchange_c
    ports:
      - '3000:3000'
    stdin_open: true #fanno partire il container in modalità interattiva
  
volumes:
  data: